'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import { SessionProvider } from "next-auth/react"
import Navbar from "@/Components/Navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
 
  return (
   
    <html lang="en" >
       
      <body className={inter.className}>
        
      <SessionProvider session={session}>
      <ThemeProvider attribute='class'>
      <Navbar/>
        {children}
       
        </ThemeProvider>
        </SessionProvider>
      </body>
     
    </html>
   
   
  )
}




